apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "exporter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "exporter.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: monitor
        image: "{{ .Values.image.imageName}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NAMESPACE
          value: "{{ .Values.namespace }}"
        - name: METRICS_PORT
          value: "{{ .Values.service.port }}"
        ports:
        - name: metrics
          containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
